/*!  http://www.logo234.com/themes/default/static/~cache/~main.js  */
function init_search(){ var def=getCookie('search'); if(def>'' && def!=G_search_def['id']){ $('.search-logo').hide(); search.change_engine(G_search_def['cid'],def); $('.search-logo').fadeIn(); }
} function set_search(def){ setCookie('search',def);
} var search={
icon_open:function(){ $('.search-toggle-icon').css("background-position","0 -6px");
},
icon_close:function(){ $('.search-toggle-icon').css("background-position","0 0px");
}, use:function(){ if(typeof search_def=="undefined" || typeof search_data=="undefined"){ window.G_search_def ={}; window.G_search_data={}; }else{ window.G_search_def =search_def; window.G_search_data=search_data; } var Othis=this; Othis.init(); init_search(); }, cate_default_id:0, init:function(){ var Othis=this; Othis.slide(); Othis.submitEvent(); search_more.init(); var domCate='.search-tab .search-cate'; $(domCate).click(function(){ $(domCate).removeClass('on'); if(!$(this).hasClass('more')){ $('#J-tab-more .a2').removeClass('on'); } $(this).addClass('on'); var cateid=$(this).attr('cateid'); Othis.change_cate(cateid); }); $('.select-list a').live('click',function(){ var cateid=$(this).attr('cateid'); var id =$(this).attr('soid'); Othis.change_engine(cateid,id); }); $('#J-search-cate-def').click(function(){ init_search(); });
}, slide_focus_status:false, slide:function(){ var Othis=this; $('.search-logo').mouseover(function(){ Othis.slide_focus_status=true; }).mouseout(function(){ Othis.slide_focus_status=false; }).click(function(){ var obj=$('.select-list'); obj.toggleClass('open'); if(obj.hasClass('open')){ Othis.icon_open(); } }); $('body').live('mouseup',function(){ if(!Othis.slide_focus_status){ Othis.icon_close(); $('.select-list').removeClass('open'); } });
},
json_firstKey:function(json){ for(var key in json){ return key; }
}, change_cate:function(cateid){ var Othis=this; var catelist=G_search_data[cateid]; if(catelist==undefined || catelist==''){ return false; } var html	=''; var tpl =document.getElementById('tpl-so-list').innerHTML; for( var idkey in catelist){ if(idkey=='def'){continue;} var row=catelist[idkey]; if((typeof row)=='object'){ var mapping={}; mapping['cateid']	=cateid; mapping['title']	=row['name']; mapping['soid'] =idkey; mapping['imgpath']	=__SO__+'/'+row['imgpath']; html+=template(tpl,mapping); } } var def=catelist['def']; if(def==undefined){ def=Othis.json_firstKey(catelist); } Othis.change_engine(cateid,def); $('.select-list').html(html);
}, change_engine:function(cateid,soid){ var data=G_search_data[cateid][soid]; if(data==undefined || data===null){ return false; } var obj=$('.search-logo'); obj.attr('title',data['name']); obj.find('img').attr('src',__SO__+'/'+data['imgpath']); $('#J-search-form').attr('action'	,data['action']); $('#J-search-name').attr('name' ,data['form_name']); var html=''; if('object'==typeof data['params']){ var params=data['params']; for(var id in params){ html+='<input type="hidden" name="'+id+'" value="'+params[id]+'"/>'; } } $('#search-params').html(html); this.curr_data=data; if(cateid==G_search_def['cid']){ set_search(soid); }
}, get_def_data:function(){ return G_search_data[G_search_def['cid']][G_search_def['id']];
}, formatId:function(id){ return id.substr(2);
}, formatCid:function(id){ return id.substr(1);
},
curr_data:undefined, submitEvent:function(){ var Othis=this; $('#J-search-form').submit(function(){ var data=Othis.curr_data; if(data==undefined || data==''){ data=Othis.get_def_data(); } var fun_submit=data['fun_submit']; if(fun_submit==''){ return true; } var submitFunc=eval('('+fun_submit+')'); if('function'!=typeof submitFunc){ return true; } var action =data['action']; var formname	=data['form_name']; var keyword =$('#J-search-name').val(); var params =data['params']; var searchtitle	=data['name']; var finalAction=submitFunc(action,formname,keyword,params,searchtitle); window.open(finalAction); return false; });
} }; var search_more={ btn_focus:false, toggleShow:function(){ var Othis=this; $('#J-tab-more-btn').mouseover(function(){ Othis.btn_focus=true; }).mouseout(function(){ Othis.btn_focus=false; }).click(function(){ $('#J-tab-more').show(); }); $('body').live('mouseup',function(){ if(!Othis.btn_focus){ $('#J-tab-more').hide(); } });
}, init:function(){ this.toggleShow(); $('#J-tab-more .a2').click(function(){ $('#J-tab-more .a2').removeClass('on'); $(this).addClass('on'); var cateid=$(this).attr('cateid'); search.change_cate(cateid); });
} };
function template(tpl,mapping){ return tpl.replace(/\{\{([a-z0-9_-]*)\}\}/ig,function(str,key){ if(mapping[key]==undefined){ return ''; }else{ return mapping[key]; } });
} function getTpl(dom){ var html=$(dom).html(); html=html.replace(/^\s*\<\!\-\-/,''); html=html.replace(/\-\-\>\s*$/,''); return html;
}
 function string2json(string){ }
function cookieKey(key){ return 'logo234_'+key;
} function setCookie(key,value,expiredays){ key=cookieKey(key); if(expiredays==undefined||expiredays==null){ expiredays=365;	} var exdate=new Date(); exdate.setDate(exdate.getDate()+expiredays); var path='/'; document.cookie=key+"="+escape(value)+((expiredays==null)?"":";expires="+exdate.toGMTString())+";path="+path;
} function getCookie(key){ key=cookieKey(key); if(document.cookie.length>0){ var start=document.cookie.indexOf(key+"="); if(start!=-1){ start=start+key.length+1; var end=document.cookie.indexOf(";",start); if(end==-1){ end=document.cookie.length; } return unescape(document.cookie.substring(start,end)); } } return "";
}
 var AngularJs={}; AngularJs.scope=function(domid){ var dom =$(domid); var element=angular.element(dom); var scope =element.scope(); return scope;
}; AngularJs.get=function(domid,key,subkey){ var scope=this.scope(domid); if(scope){ if(subkey>''){ return scope[key][subkey]; }else{ return scope[key]; } }else{ return null; }
}; AngularJs.set=function(domid,key,value,subkey){ var scope=this.scope(domid); if(scope){ if(subkey>''){ scope[key][subkey]=value; }else{ scope[key]=value; } setTimeout(function(){ scope.$apply(); },1); return true; } return false;
}; AngularJs.update=function(domid,varName,value){ var scope=this.scope(domid); if(scope){ for (var k in value){ scope[varName][k]=value[k]; } scope.$apply(); return true; } return false;
}; 
function draggable(){
var obj=new Drag(); obj.init();
}
function Drag(){ this.wrap='#ui_load_wraper'; this.move='#ui_load_title'; this.init=function(){ var bool=false; var wrap=this.wrap; $(this.move).mousedown(function(d){ bool=true; var position=$(wrap).offset(); var y=position.top; var x=position.left; y=d.pageY-y; x=d.pageX-x; $(document).bind("selectstart",function(){return false;}); $(document).mousemove(function(e){ if(!bool) return false; y_f=e.pageY-y; x_f=e.pageX-x; if(y_f<=0) y_f=0; if(x_f<=0) x_f=0; x_max=$(window).width()-$(wrap).outerWidth(); y_max=$(window).height()-$(wrap).outerHeight(); if(y_f>=y_max) y_f=y_max; if(x_f>=x_max) x_f=x_max; $(wrap).css({'position':'fixed','left':x_f+'px','top':y_f+'px','display':'block'}); }).mouseup(function(){ bool=false; }); }).mouseup(function(){ bool=false; $(document).bind("selectstart",function(){return true; }); }); };
} var copyText = function(str){ if(browerKernel.isIE()){ clipboardData.setData('Text', str); alert("站点链接已经复制到你的粘贴板中\n您可使用CTRL+V粘贴"); }else{ prompt("您的浏览器不支持自动复制,请按CTRL+C手动复制:", str); }
};
var setHome=function(obj,hostname){ if(!browerKernel.isIE()){ alert("您的浏览器不支持自动设置主页，请使用浏览器菜单手动设置。"); return false; } var host = hostname; if(!host){ host = window.location.href; } obj.style.behavior = 'url(#default#homepage)'; obj.setHomePage(host);
};
var UA = navigator.userAgent.toLowerCase();
var browerKernel = { isIE : function(){ if(/msie/i.test(UA) && !/opera/.test(UA)) return true; else return false; } }; var skin_config={ cookie_bg :'bg', cookie_bg_tile	:'bg_tile', cookie_color	:'color' }; function init_bg(){ var bg	=skinSetting.getBg(); var tile=skinSetting.getTile(); skinSetting.showBg(bg,tile);
}
function set_color(color){ init_color(color);
} function init_color(color){ if(color==undefined){ color=getCookie(skin_config.cookie_color); } if(color){ $('#style').attr('href',__C.StylePath+'/'+color+'.css'); }
} function init_skin_opacity(){ var percent=getCookie('skin_opacity'); var opacity=percentBar.getOpacity(percent); percentBar.applyOpacity(opacity);
} var skin={ path:'/skins/setting', showWindows:function(){ ui.load('个性设置',__WWWROOT__+this.path+'/index.html'); }, background:function(){ ui.load('设置背景/颜色',__WWWROOT__+this.path+'/index.html'); }, linkopen:function(){ ui.load('设置打开链接的方式',__WWWROOT__+this.path+'/linkopen.html'); }, setBg:function(filename,tile){ setCookie(skin_config.cookie_bg ,filename); setCookie(skin_config.cookie_bg_tile,tile); init_bg(filename,tile); }, changeCateFocus:function(cateid,obj){ $('.list_cate_li').removeClass('hover'); $(obj).addClass('hover'); $('#J-bg-list').find('ul').hide(); }, changeCate:function(cateid,obj){ this.changeCateFocus(cateid,obj); if($('#J-bg-list-'+cateid).html()>''){ $('#J-bg-list-'+cateid).show(); }else{ $.get(U_bg_cate(cateid),function(txt){ $('#J-bg-list').append(txt); }); } }, customCate:function(cateid,obj){ this.changeCateFocus(cateid,obj); $('#J-bg-list-custom').toggle(); }
}; var skinStyle={ setColor:function(color){ var before_color=getCookie('color'); if(color==null||color==''||color==undefined){ if(before_color){ $('.'+before_color).addClass(before_color+'-hover'); } return false; } if(before_color){ $('.'+before_color).attr('class',before_color); } $('.'+color).addClass(color+'-hover'); setCookie('color',color); set_color(color); }
};

var skin_setting_config={ cookie_bg :'bg', cookie_bg_tile	:'bg_tile', cookie_bg_custom:'bg_custom', cookie_color	:'color' }; var skinSetting={ getBg:function(){ var bg=getCookie(skin_setting_config.cookie_bg_custom); if(bg==''){ bg=getCookie(skin_setting_config.cookie_bg); if(bg>''){ bg=__BGB__+'/'+bg; } } return bg; }, getTile:function(){ return getCookie(skin_setting_config.cookie_bg_tile); }, applyBg:function(bg,tile){ setCookie(skin_setting_config.cookie_bg ,bg); setCookie(skin_setting_config.cookie_bg_tile,tile); bg=__BGB__+'/'+bg; this.showBg(bg,tile); }, showBg:function(bg,tile){ var is_tile='no-repeat'; if(tile>null){ is_tile='repeat'; } if(bg>''){ $('body').css({ 'background-image' :'url("'+bg+'")', 'background-position'	:'50% 0%', 'background-repeat' :is_tile }); }else{ $('body').css({ 'background-image' :'', 'background-position'	:'', 'background-repeat' :'' }); } } }; var skinClear={ clearBg:function(){ if(!confirm('清除背景图片设置？且不可恢复...')){ return false; } this.clearCookie(["bg_tile","bg","bg_custom"]); ui.load_close(); ui.success('重置成功...',location.href); }, clearStyle:function(){ if(!confirm('清除配色设置？且不可恢复...')){ return false; } this.clearCookie(["color"]); ui.load_close(); ui.success('重置成功...',location.href); }, clearOpacity:function(){ if(!confirm('清除不透明度设置？且不可恢复...')){ return false; } this.clearCookie(["skin_opacity"]); ui.load_close(); ui.success('重置成功...',location.href); }, clearAll:function(){ if(!confirm('清除所有配置？包括皮肤背景、配色、透明度，且不可恢复...')){ return false; } this.clearCookie(["bg_tile","bg","bg_custom","color","skin_opacity"]); ui.load_close(); ui.success('重置成功...',location.href); }, clearCookie:function(cookie){ for( var i in cookie){ setCookie(cookie[i],'',-1); }
} };

var skinCustom={ customBg:function(){ var url=$('#J-bg-custom-input').val(); setCookie('bg_custom',url); skinSetting.showBg(url,0); }, loadUrl:function(dom){ var url=getCookie('bg_custom'); $(dom).val(url); }
};
var percentBar={ btn_length :14,	bar_length :80,	use_length :null,	percent :0,
cache_paddingleft	:0, prepixel :null, cssleft :0, status_btnfocus :false, dom_bar :'J-percent-bar',
dom_btn :'J-percent-btn',
dom_num :'J-percent-num', config:function(){ this.use_length=this.bar_length-this.btn_length; this.prepixel=this.use_length/100;
}, callbackMoving:function(){ this.applyOpacity();
}, callbackDone:function(){ setCookie('skin_opacity',this.percent);
},
initBtnLoc:function(){ var percent=getCookie('skin_opacity'); if(percent==''){ percent=0; } var cssleft=percent*(this.use_length/100); this.setPercent(percent); this.setBtnLoc(cssleft);
}, setBtnLoc:function(cssleft){ if(cssleft!=undefined){ this.cssleft=cssleft; } $('#'+this.dom_btn).css({'left':this.cssleft});
},
setPercent:function(percent){ if(percent!=undefined){ this.percent=percent; } $('#'+this.dom_num).html(this.percent+'%');
}, getOpacity:function(percent){ if(percent==undefined){ var percent=this.percent; } return (100-percent)/100;
}, getPercent:function(){ var cssleft=this.cssleft; cssleft=cssleft*(100/this.use_length); this.percent=Math.round(cssleft);	return this.percent;
}, applyOpacity:function(opacity){ if(opacity==undefined){ var opacity=this.getOpacity(); } $('body').css({'opacity':opacity});
}, init:function(){ var Othis=this; Othis.config(); Othis.initBtnLoc(); $('#'+Othis.dom_btn).mousedown(function(){ Othis.status_btnfocus=true; $(document).bind("selectstart",function(){return false;}); }).mouseout(function(){ }).mouseup(function(){ }); $(document).mouseup(function(){ Othis.status_btnfocus=false; Othis.callbackDone(); $(document).bind("selectstart",function(){return true;}); }); Othis.eventMove();
}, eventMove:function(){ var Othis=this; $(document).mousemove(function(e){ if(Othis.status_btnfocus==false){ return false; } var x=e.pageX; var y=e.pageY; Othis.callbackMoving(); if(x<Othis.cache_paddingleft){ Othis.cssleft=Othis.cssleft-Othis.prepixel; }else{ Othis.cssleft=Othis.cssleft+Othis.prepixel; } if(Othis.cssleft<0){ Othis.cssleft=0; } if(Othis.cssleft>Othis.use_length){ Othis.cssleft=Othis.use_length; } Othis.setBtnLoc(); Othis.getPercent(); Othis.setPercent(); Othis.cache_paddingleft=x; });
} };

var site_plus={ use:function(){ this.icon(); this.box(); }, opacity :'0.4', domIcon :'.site-plus-icon', domBox :'.site-plus-box', domBoxUp	:'site-plus-box-up', domBoxDown	:'site-plus-box-down', box:function(){ var Othis=this; $(document).on('mouseover',Othis.domBox,function(){ $(this).show(); $(this).parents('li').css('z-index',2); $(this).prev(Othis.domIcon).css('opacity',1); }); $(document).on('mouseout',Othis.domBox,function(){ $(this).hide(); $(this).parents('li').css('z-index',1); $(this).prev(Othis.domIcon).css('opacity',Othis.opacity); }); }, boxshow:function(domIcon){ var Othis	=this; var domBox	=$(domIcon).next(Othis.domBox); var position=$(domIcon).offset(); var y =position.top; var y_max	=$(window).height()-domBox.outerHeight(); y_max	-=20; domBox.show(); $(domBox).parents('li').css('z-index',2); if(y<y_max){ domBox.removeClass(Othis.domBoxUp).addClass(Othis.domBoxDown); } }, boxhide:function(domIcon){ var Othis=this; var domBox=$(domIcon).next(Othis.domBox); $(domBox).parents('li').css('z-index',1); domBox.hide(); }, domboxHide_OFF:function(dom){ }, icon:function(){ var Othis=this; $(document).on('mouseover',Othis.domIcon,function(){ $(this).css('opacity','1'); Othis.boxshow(this); }); $(document).on('mouseout',Othis.domIcon,function(){ $(this).css('opacity',Othis.opacity); Othis.boxhide(this); }); }
};
var customize={ sites_cache:{}, move_bg:'<div class="customize-move-bg" ></div>', domTmp:'J-customizing-id', editBtn:function(){ var html='<a class="site-edit" href="javascript:void(0);" onclick="customize.change(this);">&nbsp;</a>'; return html; }, init:function(){ var Othis=this; $('#J-sites-wrap').find('li').not('.not').each(function(key){ $(this).append(Othis.editBtn()); }); $('#J-ilogo234-01').hide(); $('#J-ilogo234-02').show(); }, change:function(obj){ $('#'+this.domTmp).attr('id',''); $(obj).parents('li').attr('id',this.domTmp); ui.load('定制网址','','',getTpl("#tpl-customize-dialog")); }, setX1:function(key){ var data=this.sites_cache[key]; var obj=$('#'+this.domTmp); if(data['logotitle']>''){ data['styletitle']	=' style="display:block;" '; data['styleimg']	=' style="display:none;" '; }else{ data['styletitle']	=' style="display:none;" '; data['styleimg']	=' style="display:block;" '; } var tpl	=document.getElementById('tpl-site-one').innerHTML; var html=template(tpl,data); html+=this.getplus(data['plus']); html+=this.editBtn(); obj.addClass('J-customizing-class'); obj.attr('idtmp',data.id); obj.html(html); ui.load_close(); }, set:function(key){ var data=this.sites_cache[key]; var obj=$('#'+this.domTmp); ICtrl.List.update(obj,data); ui.load_close(); }, getplus:function(plus){ if(plus==''){ return ''; } var tpl =document.getElementById('tpl-site-plus').innerHTML; var plus	=eval('('+plus+')'); var listTpl	='<a target="_blank" href="{{url}}">{{title}}</a>'; var ListHtml=''; for( var url in plus){ var params={}; params['url']	=url; params['title']	=plus[url]; ListHtml+=template(listTpl,params); } var html=template(tpl,{'plusList':ListHtml}); return html; }, apply:function(){ if(!confirm('确定应用？您之前定制的所有网址都将被覆盖，且不可恢复...')){ return false; } customize_cookie.save(); ui.success('应用成功',__I__); }, reset:function(){ if(confirm('确定重置？您之前定制的所有网址都将丢失，且不可恢复...')){ customize_cookie.clear(); ui.success('重置成功...',__I__); } }, cancel:function(){ window.location.reload(); }, finish:function(){ customize_cookie.save(); window.location.reload(); }
};
var customize_cookie={ cookie_name:'customize', clear:function(){ setCookie(this.cookie_name,'',-1); }, set:function(value){ setCookie(this.cookie_name,value); }, get:function(){ return getCookie(this.cookie_name); }, save:function(){ var cookie=this.getIds(); this.set(cookie); }, getIds:function(){ var ids=''; $('#J-sites-wrap').find('li').not('.not').each(function(){ var id=$(this).attr('idtmp'); if(id>0){ ids=ids+','+id; } }); ids=ids.slice(1); return ids; }, share:function(){ var ids=this.get(); if(ids==''){ ui.error('你没有定制网址'); return; } var data={}; data['url']='loading...'; var tpl	=document.getElementById('tpl-customize-share').innerHTML; var html=template(tpl,data); ui.load('分享我的定制','','',html); var url=__I__+'/share.php'; $.post(url,{},function(txt){ txt=eval('('+txt+')'); var success=txt.success; var message=txt.message; var input =''; if(success){ input=__I__+'/?s='+txt.shortUrl; }else{ input=message; } var data={}; data['url']=input; var html=template(tpl,data); ui.load('分享我的定制','','',html); }); }
};
var customize_search={ use:function(){ var Othis=this; $('#J-site-search-form').submit(function(){ Othis.query(this); return false; }); }, query:function(domForm){ var Othis=this; var url =__I__+'/search.php'; var params ={}; params['keyword']	=$(domForm).find('[name=keyword]').val(); params['type'] =$(domForm).find('[name=type]').val(); if(params['keyword']==''){ Othis.resList('请输入关键字...'); return false; } $.post(url,params,function(txt){ txt=eval('('+txt+')'); Othis.resList(txt.list); }); }, resList:function(datas){ var html=''; if(typeof datas=='object'){ customize.sites_cache=datas; var tpl	=document.getElementById('tpl-site-search-list').innerHTML; for( var id in datas){ datas[id]['key']=id; html+=template(tpl,datas[id]); } }else{ html=datas; } $('#J-site-search-list').html(html); }, hot_keyword:function(obj){ var value	=$(obj).html(); var domForm	=$('#J-site-search-form'); domForm.find('[name=keyword]').val(value); domForm.find('[name=type]').val('name'); domForm.submit(); }
}; var ilogo234={ share:function(){ customize_cookie.share(); }, skin:function(){ skin.background(); }, customize:function(){ customize.init(); }, add_customizeX1:function(obj){ var length=$('#J-sites-wrap').find('li').not('.not').length; if(length>24-2){ } var dom =$(obj).parents('li'); var tpl	=document.getElementById('tpl-addsite-one').innerHTML; dom.before(tpl); customize.init(); dom.prev('li').find('.site-edit').click(); }, add_customize:function(obj){ var length=$('#J-sites-wrap').find('li').not('.not').length; if(length>24-2){ } ICtrl.List.push({'logotitle':'选择网址','title':'选择网址'}); setTimeout(function(){ customize.init(); var dom =$(obj).parents('li'); dom.prev('li').find('.site-edit').click(); },10); }
}; var ICtrl={}; ICtrl.List={}; ICtrl.List.push=function(data){ var iCtrl=$('[ng-controller="ICtrl"]'); var list =AngularJs.get(iCtrl,'list'); list.push(data); AngularJs.set(iCtrl,'list',list);
}; ICtrl.List.updateX1=function(dom,data){ AngularJs.set(dom,'row',data);
}; ICtrl.List.update=function(dom,data){ var row=AngularJs.get(dom,'row'); var $idx=row.$index; var iCtrl=$('[ng-controller="ICtrl"]'); var list =AngularJs.get(iCtrl,'list'); list[$idx]=data; AngularJs.set(iCtrl,'list',list);
}; function set_resetall(){ if(!confirm('确定重置所有设置？背景,配色,和定制的网站等均会丢失，且不可恢复...')) return false; var arr=new Array('logo234_customize','logo234_bg_tile','logo234_bg','logo234_color','logo234-search'); for (var i in arr){ setCookie(arr[i],'',-1); } ui.load_close(); ui.success('重置成功...',location.href); }
var about={ menuChange:function(id,obj){ if(!id){ var anchor=window.location.hash.slice(1); }else{ var anchor=id; } if(anchor>0){ var len=document.anchors.length; if(anchor>len){ anchor=len; } for( var j=0;j<len;j++){ var dom=document.anchors[j]; dom.className=''; } var dom2=document.anchors[anchor-1]; dom2.className='hover'; for( var i=1;i<=len;i++){ document.getElementById('item'+i).style.display='none'; } document.getElementById('item'+anchor).style.display='block'; }else{ var obj=document.getElementById('item1'); obj.style.display='block'; } }
};

var feedback={ getLength:function(str){ return str.replace(/^\s+|\s+$/ig,'').replace(/[^\x00-\xff]/ig,'x').length; }, use:function(){ var Othis=this; $('#form-feedback').submit(function(){ Othis.submit(this); }); }, submit:function(domForm){ var Othis=this; var params ={}; params['name'] =document.getElementById('J-form-name').value; params['email'] =document.getElementById('J-form-email').value; params['content']	=document.getElementById('J-form-content').value; if(!this.validate(params)){ return false; } var action=domForm.action; $.post(action,params,function(txt){ txt = eval("(" + txt + ")"); if(txt['success']>0){ ui.success(txt['message']); ui.reload(); }else{ Othis.error(txt['message']); } }); return false; }, validate:function(params){ if(this.getLength(params['name'])>20){ this.error(this.message.name); return false; } if(!params['email'].match(/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/)){ this.error(this.message.email); return false; } if(this.getLength(params['content'])>200 || this.getLength(params['content'])<10){ this.error(this.message.content); return false; } this.error('',true); return true; }, message:{ name	:'昵称0-20字符', email	:'联系邮箱格式错误(必填)', content :'意见内容10~200字符(必填)' }, error:function(message,realmessage){ var dom=document.getElementById('J-error'); if(realmessage==undefined){ dom.innerHTML='&nbsp;!出错：'+message; }else{ dom.innerHTML=message; } } };
var submit={ use:function(){ var Othis=this; document.getElementById('form-submit').onsubmit=function(){ Othis.submit(this); return false; }; }, submit:function(domForm){ if(!this.validate()){ return false; } var params=$(domForm).serializeArray(); var action=domForm.action; $.post(action,params,function(txt){ txt = eval("(" + txt + ")"); if(txt['success']>0){ ui.success(txt['message']); ui.reload(); }else{ ui.error(txt['message']); } }); return false; }, validate:function(params){ var Othis=this; var msg={}; msg['name'] ='网站名称必填'; msg['url'] ='网站地址必填'; msg['email']	='联系邮箱必填'; msg['verify']	='验证码必填'; for(var i in msg){ var value=(document.getElementsByName(i))[0].value; if(value==''){ ui.error(msg[i]); return false; } } return true; }, error:function(message,realmessage){ }
};var ui={
success:function(message,url,error){ var s_e_class=(error==1)?"ui_success_box ui_error_box":"ui_success_box"; var html="<div id='ui_box' class='"+s_e_class+"'><div id='ui_messagecontent'>"+message+"</div></div>"; var show=function(){ var bg='<div class="box_bg" style="width: 100%; height:'+jQuery(document).height()+'px; z-index: 999;filter: alpha(opacity=35);-moz-opacity: 0.35;opacity: 0.35;"></div>'; $('body').append(html); $('body').append(bg); var v=ui._viewport(); $('#ui_box').css({ 'left':(v.left+v.width/2-$('#ui_box').outerWidth()/2)+"px", 'top':(v.top+v.height/2-$('#ui_box').outerHeight()/2)+"px" }); }; var closeFun=function(){ setTimeout(function(){ $('#ui_box').fadeOut("fast",function(){ jQuery('.box_bg').remove(); jQuery('#ui_box').remove(); if(url>''){ location.href=url; } }); },1000); }; show(); closeFun();
}, error:function(message){ ui.success(message,'',1);
}, confirm:function(obj,text){ var callback=$(obj).attr('callback'); text=text||'确定执行此操作？'; html='<div id="qc_ui_confirm" class="ui_confirm">'+'<a class="del" href="javascript:void(0)" onclick="$(\'#qc_ui_confirm\').remove()"></a>'+'<div class="txt"></div>'+'<div class="button"><input type="button" value="确定" class="btn"><input type="button" value="取消" class="btn_w"></div>'+'</div>'; $('body').append(html); var position=$(obj).offset(); $('#qc_ui_confirm').css({ "top":position.top+"px", "left":position.left-($("#qc_ui_confirm").width()/2)+"px", "display":"none" }); $("#qc_ui_confirm .txt").html(text); $('#qc_ui_confirm').fadeIn("fast"); $("#qc_ui_confirm .btn_w").one('click',function(){ $('#qc_ui_confirm').fadeOut("fast"); $('#qc_ui_confirm').remove(); }); $("#qc_ui_confirm .btn").one('click',function(){ $('#qc_ui_confirm').fadeOut("fast"); $('#qc_ui_confirm').remove(); eval(callback);	});
},
load:function(title,url,data,inputhtml){ $('.ui_load').remove(); var loading='<div class="ui_loading"></div>'; var html='<div id="ui_load_wraper" class="ui_load">'+'<div id="ui_load_title" class="title"><h3>'+title+'</h3><a class="del" href="javascript:void(0)" onclick="$(\'.ui_load\').remove()"></a></div>'+'<div class="ui_load_content">'+loading+'</div>'+'</div>'; $('body').append(html); var v=ui._viewport(); var objBox=$('.ui_load'); objBox.css({ 'left':(v.left+v.width/2-objBox.outerWidth()/2)+"px", 'top':(v.top+v.height/2-objBox.outerHeight()/2)+"px" }); if(inputhtml>0||inputhtml>''){ $('.ui_load_content').html(inputhtml); objBox.css({ 'left':(v.left+v.width/2-objBox.outerWidth()/2)+"px", 'top':(v.top+v.height/2-objBox.outerHeight()/2)+"px" }); }else{ if(!data) data=''; $.get(url,{ data:data },function(txt){ $('.ui_load_content').html(txt); objBox.css({ 'left':(v.left+v.width/2-objBox.outerWidth()/2)+"px", 'top':(v.top+v.height/2-objBox.outerHeight()/2)+"px" }); }); } draggable(); }, load_close:function(){ $('.ui_load').remove();
},
_viewport:function(){ var d=document.documentElement,b=document.body,w=window; return jQuery.extend(jQuery.browser.msie?{ left:b.scrollLeft||d.scrollLeft, top:b.scrollTop||d.scrollTop }:{ left:w.pageXOffset, top:w.pageYOffset },!ui._u(w.innerWidth)?{ width:w.innerWidth, height:w.innerHeight }:(!ui._u(d)&&!ui._u(d.clientWidth)&&d.clientWidth!=0?{ width:d.clientWidth, height:d.clientHeight }:{ width:b.clientWidth, height:b.clientHeight }));
},
_u:function(){ for( var i=0;i<arguments.length;i++) if(typeof arguments[i]!='undefined') return false; return true;
}, reload:function(time){ if(time==''||time==undefined) time=600; setTimeout('location.reload()',time);}
};if(typeof angular!='undefined'){ var logoApp = angular.module('logoApp', [ 'logoApp.controllers', 'logoApp.filters' ]); var logoCtrl=angular.module('logoApp.controllers', []); var logoFilter=angular.module('logoApp.filters', []);
}
if(typeof angular!='undefined'){ logoFilter.filter('to_trusted',['$sce',function($sce){ return function (text){ return $sce.trustAsHtml(text); } }]); logoFilter.filter('to_trustAsHtml',['$sce',function($sce){ return function(text){ return $sce.trustAsHtml(text); } }]);
}

function GetQueryString(name){ var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)"); var r = window.location.search.substr(1).match(reg); if(r!=null)return unescape(r[2]); return null;
} if(typeof angular!='undefined'){ logoCtrl.controller('ICtrl', function($scope,$rootScope,$http,$filter,$timeout){ $scope.list={}; var share=GetQueryString('s'); var url=__I__+'/i.php'; $http({ method : 'POST', url : url, data : $.param({'s':share}), headers : { 'Content-Type': 'application/x-www-form-urlencoded' } }) .success(function(data){ var success =data.success; var message =data.message; if(success){ $rootScope.isShare=data.isShare; $scope.list =data.list; } }); });
}if(typeof angular!='undefined'){ logoCtrl.controller('LocalCtrl', function($scope,$rootScope,$http,$timeout){ $scope.ispreview=false; });
}

window.__C={}; __C.StylePath=__JSTATIC__+'/styles'; $(document).ready(function(){ site_plus.use();
}); function onload_body(){ init_bg(); init_color(); init_skin_opacity();
} onload_body();
search.use();